# Python logging configuration for all project modules.
# Usage: load with logging.config.dictConfig when apps start.

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

loggers:
  # Library/module loggers can be tuned here
  kafka: { level: WARNING, handlers: [console], propagate: false }
  pyspark: { level: WARNING, handlers: [console], propagate: false }

root:
  level: INFO
  handlers: [console]
